### ISSUE TITLE
Composer based installations

### ISSUE THREAD

**Issue by chris-brabender** [comwrap/Comwrap_ElasticsuiteBlog#1]
Can you please update this repository to support composer based installations more easily?

EG: Include in packagist, add a tag and remove the restrictive php requirements?

`"php": "~5.5.0|~5.6.0|~7.0.0",`

Thanks!

**Comment by nuzil** [comment]
Hey @chris-brabender 
Thanks for this issue, we will take care of it, its a good idea

**Comment by nuzil** [comment]
We removed php dependency.
Thanks for your note
