### ISSUE TITLE
Template not showing on blog result page

### ISSUE THREAD

**Issue by stb** [comwrap/Comwrap_ElasticsuiteBlog#10]
Tested on Magento 2.3.1 & 2.3.2 with latest Comwrap_ElasticsuiteBlog. When calling the Result Page, pthml not loaded.

**Comment by stb** [comment]
After renaming layout file from smile_elasticsuite_blog_result_index.xml to comwrap_elasticsuite_blog_result_index Index Page is working.

**Comment by nuzil** [comment]
Hi @stb , we will have a look on that

**Comment by Amadeco** [comment]
Same problem on Magento 2.3.3
Thank you @stb for the solution.
