### ISSUE TITLE
Indexer using wrong handler "string" not "text" for newer version elasticsearch

### ISSUE THREAD

**Issue by petitgen** [comwrap/Comwrap_ElasticsuiteBlog#2]
Hi there,

When I reindex I got this issue :

```
Elasticsuite Blog Indexing indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [title]"}],"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [title]"},"status":400}
```

as the newer version of elasticsearch dropped the handler "string",
as explained there: 
https://stackoverflow.com/a/47454366
So we have to modify this file :
https://github.com/comwrap/Comwrap_ElasticsuiteBlog/blob/master/etc/elasticsuite_indices.xml#L9
for `title` and `content` fields

Cheers,

Sebastien

**Comment by petitgen** [comment]
I did a PR : https://github.com/comwrap/Comwrap_ElasticsuiteBlog/pull/3

if someone could review it ;-),

Cheers,

Seb

**Comment by nuzil** [comment]
Thanks a lot, PR is merged
