### ISSUE TITLE
Integrate this add on with Blog MX for Magento 2 possible?

### ISSUE THREAD

**Issue by VivekShingala** [comwrap/Comwrap_ElasticsuiteBlog#6]
Hi

We are using **Blog MX for Magento 2** blog module for our Magento 2 store. Is it possible to integrate this add on with this blog module created by Mirasvit?

Extension Link: https://mirasvit.com/magento-2-extensions/blog.html

We are using elasticsuite for search and layered navigation.

**Comment by nuzil** [comment]
Hi @VivekShingala 
technically definitely possible, but not for this extension. To integrate it in Mirasvit module, we need to make a new extension then.
